#!/usr/bin/expect
spawn /root/modelsim_src/ModelSimSetup-13.1.0.162.run
expect {
    "Press * to continue*" { send "\r"
                                    exp_continue
                           }
    "Select the ModelSim edition you like to install*" { send "1\r"
                                                          exp_continue
                                                       }
    "Do you accept this license?*" { send "y\r"
                                      exp_continue
                                   }
    "Installation Directory *" { send "\r"
                                 exp_continue
                               }
}
